import '../models/comportamiento.dart'; // Asegúrate que apunte bien

final List<String> comportamientosClaves = [
  'Soporte',
  'Reconocer',
  'Comunidad',
  'Liderazgo de Servidor',
  'Valorar',
  'Empoderamiento',
  'Mentalidad',
  'Estructura',
  'Reflexionar',
  'Análisis',
  'Colaborar',
  'Comprender',
  'Diseño',
  'Atribución',
  'A prueba de error',
  'Propiedad',
  'Conectar',
  'Ininterrumpido',
  'Demanda',
  'Eliminar',
  'Optimizar',
  'Impacto',
  'Alinear',
  'Aclarar',
  'Comunicar',
  'Relación',
  'Medida',
  'Valor',
];